name: Send Feedback

on:
  issues:
    types: [opened]
  push:
    branches: [master]

jobs:
  send_feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Send feedback to GitHub
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const feedback = `**Feedback from ${context.payload.issue.user.login}:**\n\n${context.payload.issue.body}`;
            const title = `New feedback from ${context.payload.issue.user.login}`;
            const newIssue = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: feedback
            });
            console.log(`New issue created: ${newIssue.data.html_url}`);
