name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: Eskabore/eskabore/trunk
        with:
          channel_id: UC-PyiQJGXmEENgm0WaQEr2w
